// Inhalte der Englisch-App fuer Kyla. IDs nie aendern (Fortschritt und gespeicherte Saetze haengen daran), neue Eintraege nur anhaengen.
// lv = Stufe (1 Gegenwart/can/there is, 2 Vergangenheit/Zukunft/because/would like, 3 Vergleich/Perfekt/if/should/Meinung).
// Chinesisch: Traditionell, Taiwan, Trenner "，", keine Gedankenstriche.

// Satz bauen: chinesischer Satz -> englischer Satz aus Kaertchen. alt = weitere richtige Reihenfolgen (gleiche Woerter).
const BAUEN = [
  {id:"b1",  lv:1, zh:"我每天早上喝咖啡。", en:"I drink coffee every morning.", alt:["Every morning I drink coffee."]},
  {id:"b2",  lv:1, zh:"我姊姊住在台北。", en:"My sister lives in Taipei."},
  {id:"b3",  lv:1, zh:"我不喜歡冷天氣。", en:"I don't like cold weather."},
  {id:"b4",  lv:1, zh:"廁所在哪裡？", en:"Where is the bathroom?"},
  {id:"b5",  lv:1, zh:"我通常搭公車去上班。", en:"I usually take the bus to work."},
  {id:"b6",  lv:1, zh:"可以請你幫我一下嗎？", en:"Can you help me, please?", alt:["Can you please help me?"]},
  {id:"b7",  lv:1, zh:"我家附近有一家超市。", en:"There is a supermarket near my home."},
  {id:"b8",  lv:1, zh:"我週末喜歡做菜。", en:"I like cooking on weekends.", alt:["On weekends I like cooking."]},
  {id:"b9",  lv:1, zh:"這個包包多少錢？", en:"How much is this bag?"},
  {id:"b10", lv:1, zh:"我今天有一點累。", en:"I am a little tired today.", alt:["Today I am a little tired."]},
  {id:"b11", lv:1, zh:"我朋友在醫院工作。", en:"My friend works in a hospital."},
  {id:"b12", lv:1, zh:"你會說中文嗎？", en:"Can you speak Chinese?"},
  {id:"b13", lv:1, zh:"我晚上常常看電視。", en:"I often watch TV in the evening.", alt:["In the evening I often watch TV."]},
  {id:"b14", lv:2, zh:"我昨天去了夜市。", en:"I went to the night market yesterday.", alt:["Yesterday I went to the night market."]},
  {id:"b15", lv:2, zh:"我們上個週末待在家裡。", en:"We stayed at home last weekend.", alt:["Last weekend we stayed at home."]},
  {id:"b16", lv:2, zh:"我想要一杯水，謝謝。", en:"I would like a glass of water, please."},
  {id:"b17", lv:2, zh:"我星期天要去看我爸媽。", en:"I'm going to visit my parents on Sunday.", alt:["On Sunday I'm going to visit my parents."]},
  {id:"b18", lv:2, zh:"我昨天晚上睡不著。", en:"I couldn't sleep last night.", alt:["Last night I couldn't sleep."]},
  {id:"b19", lv:2, zh:"她打電話給我，因為她需要幫忙。", en:"She called me because she needed help."},
  {id:"b20", lv:2, zh:"你喜歡那部電影嗎？", en:"Did you enjoy the movie?"},
  {id:"b21", lv:2, zh:"不好意思，我沒聽懂。", en:"I'm sorry, I didn't understand that."},
  {id:"b22", lv:2, zh:"你可以說慢一點嗎？", en:"Could you speak a little slower?"},
  {id:"b23", lv:2, zh:"我明天打給你。", en:"I'll call you tomorrow.", alt:["Tomorrow I'll call you."]},
  {id:"b24", lv:2, zh:"火車幾點開？", en:"What time does the train leave?"},
  {id:"b25", lv:2, zh:"我把手機忘在家裡了。", en:"I forgot my phone at home."},
  {id:"b26", lv:2, zh:"我們跟朋友一起吃了晚餐。", en:"We had dinner with our friends."},
  {id:"b27", lv:3, zh:"這家餐廳比另一家便宜。", en:"This restaurant is cheaper than the other one."},
  {id:"b28", lv:3, zh:"我從來沒去過日本。", en:"I have never been to Japan."},
  {id:"b29", lv:3, zh:"如果下雨，我們就待在家裡。", en:"If it rains, we will stay at home.", alt:["We will stay at home if it rains."]},
  {id:"b30", lv:3, zh:"我小時候住在台南。", en:"When I was a child, I lived in Tainan.", alt:["I lived in Tainan when I was a child."]},
  {id:"b31", lv:3, zh:"你應該多喝水。", en:"You should drink more water."},
  {id:"b32", lv:3, zh:"我覺得英文比德文簡單。", en:"I think English is easier than German."},
  {id:"b33", lv:3, zh:"你吃過臭豆腐嗎？", en:"Have you ever tried stinky tofu?"},
  {id:"b34", lv:3, zh:"我住在這裡十年了。", en:"I have lived here for ten years."},
  {id:"b35", lv:3, zh:"那是我這輩子最棒的一次旅行。", en:"It was the best trip of my life."},
  {id:"b36", lv:3, zh:"我不同意，因為太貴了。", en:"I don't agree, because it is too expensive."},
  {id:"b37", lv:3, zh:"飯店不錯，但是房間太小了。", en:"The hotel was nice, but the room was too small."},
];

// Satzmuster: Anfang vorgegeben, Kyla ergaenzt mit eigenem Inhalt und sagt den ganzen Satz.
const MUSTER = [
  {id:"m1",  lv:1, en:"On weekends I usually ___.", zh:"週末我通常……", ex:"On weekends I usually sleep late and meet my friends."},
  {id:"m2",  lv:1, en:"In the morning I ___.", zh:"早上我……", ex:"In the morning I drink tea and read the news."},
  {id:"m3",  lv:1, en:"I don't like ___.", zh:"我不喜歡……", ex:"I don't like crowded places."},
  {id:"m4",  lv:1, en:"My favorite food is ___.", zh:"我最喜歡的食物是……", ex:"My favorite food is beef noodle soup."},
  {id:"m5",  lv:1, en:"I can ___, but I can't ___.", zh:"我會……，但是我不會……", ex:"I can cook, but I can't bake a cake."},
  {id:"m6",  lv:1, en:"There is a ___ near my home.", zh:"我家附近有……", ex:"There is a nice park near my home."},
  {id:"m7",  lv:1, en:"Every day I ___.", zh:"我每天……", ex:"Every day I walk for thirty minutes."},
  {id:"m8",  lv:1, en:"I'm good at ___.", zh:"我很會……", ex:"I'm good at cooking."},
  {id:"m9",  lv:1, en:"My home is ___.", zh:"我家……", ex:"My home is small, but it's very bright."},
  {id:"m10", lv:1, en:"I often ___ with my friends.", zh:"我常常跟朋友……", ex:"I often go hiking with my friends."},
  {id:"m11", lv:1, en:"During the day I ___.", zh:"白天我……", ex:"During the day I work, and in the evening I relax."},
  {id:"m12", lv:1, en:"I want to learn ___.", zh:"我想學……", ex:"I want to learn how to make bread."},
  {id:"m13", lv:1, en:"My best friend is ___.", zh:"我最好的朋友……", ex:"My best friend is funny and very kind."},
  {id:"m14", lv:1, en:"I never ___.", zh:"我從來不……", ex:"I never eat breakfast at home."},
  {id:"m15", lv:2, en:"Yesterday I ___.", zh:"昨天我……", ex:"Yesterday I cleaned the house and watched a movie."},
  {id:"m16", lv:2, en:"Last weekend I ___.", zh:"上個週末我……", ex:"Last weekend I went to the beach with my family."},
  {id:"m17", lv:2, en:"Tomorrow I'm going to ___.", zh:"明天我要……", ex:"Tomorrow I'm going to visit a friend."},
  {id:"m18", lv:2, en:"I would like to ___ one day.", zh:"有一天我想……", ex:"I would like to visit Iceland one day."},
  {id:"m19", lv:2, en:"I really like ___ because ___.", zh:"我很喜歡……，因為……", ex:"I really like rainy days because I can stay at home and read."},
  {id:"m20", lv:2, en:"When I was young, I ___.", zh:"我小時候……", ex:"When I was young, I played outside every day."},
  {id:"m21", lv:2, en:"This morning I ___.", zh:"今天早上我……", ex:"This morning I made breakfast and took the MRT."},
  {id:"m22", lv:2, en:"Excuse me, could you ___?", zh:"不好意思，你可以……嗎？", ex:"Excuse me, could you take a photo of us?"},
  {id:"m23", lv:2, en:"I'd like ___, please.", zh:"我想要……，謝謝。", ex:"I'd like a table for two, please."},
  {id:"m24", lv:2, en:"I was very happy when ___.", zh:"……的時候，我很開心。", ex:"I was very happy when my friend visited me."},
  {id:"m25", lv:2, en:"Next year I want to ___.", zh:"明年我想……", ex:"Next year I want to travel to Korea."},
  {id:"m26", lv:2, en:"I didn't ___ because ___.", zh:"我沒有……，因為……", ex:"I didn't go out because it was raining."},
  {id:"m27", lv:2, en:"Last year I ___.", zh:"去年我……", ex:"Last year I started a new job."},
  {id:"m28", lv:3, en:"I have never ___.", zh:"我從來沒有……過", ex:"I have never been to Europe."},
  {id:"m29", lv:3, en:"___ is better than ___ because ___.", zh:"……比……好，因為……", ex:"Tea is better than coffee because it doesn't make me nervous."},
  {id:"m30", lv:3, en:"If I had more time, I would ___.", zh:"如果我有更多時間，我會……", ex:"If I had more time, I would learn to play the piano."},
  {id:"m31", lv:3, en:"In my opinion, ___.", zh:"我認為……", ex:"In my opinion, Taipei is a great city for families."},
  {id:"m32", lv:3, en:"I think you should ___.", zh:"我覺得你應該……", ex:"I think you should take a break."},
  {id:"m33", lv:3, en:"The best thing about ___ is ___.", zh:"……最棒的地方是……", ex:"The best thing about my neighborhood is the food."},
  {id:"m34", lv:3, en:"I have known ___ for ___ years.", zh:"我認識……已經……年了。", ex:"I have known my best friend for twenty years."},
  {id:"m35", lv:3, en:"When I travel, I always ___.", zh:"我旅行的時候，總是……", ex:"When I travel, I always try the local food."},
  {id:"m36", lv:3, en:"If it's sunny tomorrow, I will ___.", zh:"如果明天天氣好，我會……", ex:"If it's sunny tomorrow, I will go to the mountains."},
  {id:"m37", lv:3, en:"It's difficult for me to ___.", zh:"對我來說，……很難。", ex:"It's difficult for me to speak English on the phone."},
  {id:"m38", lv:3, en:"I used to ___, but now I ___.", zh:"我以前……，但是現在……", ex:"I used to drink a lot of coffee, but now I drink tea."},
  {id:"m39", lv:3, en:"The most beautiful place I have ever seen is ___.", zh:"我看過最美的地方是……", ex:"The most beautiful place I have ever seen is Taroko Gorge."},
  {id:"m40", lv:3, en:"I'm not sure, but I think ___.", zh:"我不確定，但是我覺得……", ex:"I'm not sure, but I think the shop closes at nine."},
];

// Fragen: frei antworten (1-2 Saetze). t: alltag | situation | meinung. start = Satzanfang-Hilfe, w = Woerter [englisch, chinesisch], ex = Beispielantwort.
const FRAGEN = [
  // Stufe 1
  {id:"q1",  lv:1, t:"alltag", en:"What do you usually eat for breakfast?", zh:"你早餐通常吃什麼？", start:"For breakfast I usually eat ...", w:[["egg pancake","蛋餅"],["soy milk","豆漿"],["toast","吐司"],["rice ball","飯糰"]], ex:"For breakfast I usually eat an egg pancake and drink soy milk."},
  {id:"q2",  lv:1, t:"alltag", en:"What do you like to do in your free time?", zh:"你有空的時候喜歡做什麼？", start:"In my free time I like to ...", w:[["go for a walk","散步"],["watch TV shows","看劇"],["read","看書"],["go shopping","逛街"]], ex:"In my free time I like to watch TV shows and go for a walk."},
  {id:"q3",  lv:1, t:"alltag", en:"Can you describe your home?", zh:"你可以描述一下你家嗎？", start:"My home is ...", w:[["apartment","公寓"],["living room","客廳"],["balcony","陽台"],["quiet","安靜"]], ex:"I live in an apartment. It has a small balcony and it's very quiet."},
  {id:"q4",  lv:1, t:"alltag", en:"What is the weather like today?", zh:"今天天氣怎麼樣？", start:"Today it is ...", w:[["hot","熱"],["humid","悶熱潮濕"],["cloudy","陰天"],["it's raining","在下雨"]], ex:"Today it is hot and humid, but it's not raining."},
  {id:"q5",  lv:1, t:"alltag", en:"What time do you usually get up?", zh:"你通常幾點起床？", start:"I usually get up at ...", w:[["early","早"],["late","晚"],["alarm clock","鬧鐘"],["on weekends","週末"]], ex:"I usually get up at seven, but on weekends I get up late."},
  {id:"q6",  lv:1, t:"alltag", en:"What do you usually do in the evening?", zh:"你晚上通常做什麼？", start:"In the evening I usually ...", w:[["cook dinner","煮晚餐"],["relax","放鬆"],["take a shower","洗澡"],["go to bed","去睡覺"]], ex:"In the evening I usually cook dinner and relax on the sofa."},
  {id:"q7",  lv:1, t:"alltag", en:"Do you like cooking? What can you cook?", zh:"你喜歡做菜嗎？你會做什麼？", start:"I like cooking. I can make ...", w:[["fried rice","炒飯"],["soup","湯"],["noodles","麵"],["dumplings","水餃"]], ex:"Yes, I like cooking. I can make fried rice and a good soup."},
  {id:"q8",  lv:1, t:"alltag", en:"How do you go to the supermarket?", zh:"你怎麼去超市？", start:"I usually go by ...", w:[["scooter","機車"],["walk","走路"],["MRT","捷運"],["bus","公車"]], ex:"I usually walk, because the supermarket is near my home."},
  {id:"q9",  lv:1, t:"alltag", en:"What do you usually buy at the supermarket?", zh:"你在超市通常買什麼？", start:"I usually buy ...", w:[["vegetables","青菜"],["fruit","水果"],["milk","牛奶"],["snacks","零食"]], ex:"I usually buy vegetables, fruit, and some snacks."},
  {id:"q10", lv:1, t:"alltag", en:"What do you like about your city?", zh:"你喜歡你住的城市的什麼？", start:"I like ...", w:[["convenient","方便"],["food","食物"],["people","人"],["mountains","山"]], ex:"I like the food, and it's very convenient."},
  {id:"q11", lv:1, t:"alltag", en:"What do you usually do on Sunday?", zh:"你星期天通常做什麼？", start:"On Sunday I usually ...", w:[["sleep late","睡晚一點"],["visit my family","去看家人"],["clean the house","打掃家裡"],["go out","出門"]], ex:"On Sunday I usually sleep late and visit my family."},
  {id:"q12", lv:1, t:"situation", en:"You are in a café. Order a drink.", zh:"你在咖啡店，點一杯飲料。", start:"Can I have ...", w:[["latte","拿鐵"],["iced","冰的"],["less sugar","少糖"],["to go","外帶"]], ex:"Can I have an iced latte with less sugar, please? To go."},
  {id:"q13", lv:1, t:"situation", en:"You are lost. Ask someone the way to the station.", zh:"你迷路了，問別人怎麼去車站。", start:"Excuse me, how do I get to ...", w:[["station","車站"],["far","遠"],["turn left","左轉"],["straight","直走"]], ex:"Excuse me, how do I get to the train station? Is it far?"},
  {id:"q14", lv:1, t:"situation", en:"You are in a shop. Ask about the price and the size.", zh:"你在店裡，問價錢和尺寸。", start:"Excuse me, how much is ...", w:[["size","尺寸"],["bigger","大一點"],["try on","試穿"],["smaller","小一點"]], ex:"Excuse me, how much is this jacket? Do you have it in a bigger size?"},
  {id:"q15", lv:1, t:"situation", en:"You meet a new neighbor. Introduce yourself.", zh:"你遇到一位新鄰居，介紹一下你自己。", start:"Hi, I'm ... I live ...", w:[["next door","隔壁"],["upstairs","樓上"],["downstairs","樓下"],["nice to meet you","很高興認識你"]], ex:"Hi, I'm Kyla. I live next door. Nice to meet you!"},
  {id:"q16", lv:1, t:"situation", en:"You are at a bakery. Buy something for breakfast.", zh:"你在麵包店，買明天的早餐。", start:"I'd like ...", w:[["bread","麵包"],["two of these","這個兩個"],["a bag","袋子"],["that's all","這樣就好"]], ex:"I'd like two of these, please. That's all, thank you."},
  // Stufe 2
  {id:"q17", lv:2, t:"alltag", en:"What did you do yesterday evening?", zh:"你昨天晚上做了什麼？", start:"Yesterday evening I ...", w:[["cooked","煮了"],["watched","看了"],["met","見了"],["went to bed","去睡覺"]], ex:"Yesterday evening I cooked dinner and watched a movie."},
  {id:"q18", lv:2, t:"alltag", en:"What did you eat for lunch today?", zh:"你今天午餐吃了什麼？", start:"For lunch I had ...", w:[["lunch box","便當"],["noodles","麵"],["salad","沙拉"],["nothing","什麼都沒吃"]], ex:"For lunch I had a lunch box with chicken and rice."},
  {id:"q19", lv:2, t:"alltag", en:"What did you do last weekend?", zh:"你上個週末做了什麼？", start:"Last weekend I ...", w:[["went","去了"],["stayed at home","待在家"],["saw","看了"],["bought","買了"]], ex:"Last weekend I stayed at home on Saturday, and on Sunday I went to a café."},
  {id:"q20", lv:2, t:"alltag", en:"What are you going to do tomorrow?", zh:"你明天要做什麼？", start:"Tomorrow I'm going to ...", w:[["work","工作"],["meet","見面"],["go shopping","去買東西"],["rest","休息"]], ex:"Tomorrow I'm going to work, and in the evening I'm going to meet a friend."},
  {id:"q21", lv:2, t:"alltag", en:"What is your favorite season? Why?", zh:"你最喜歡哪個季節？為什麼？", start:"My favorite season is ... because ...", w:[["spring","春天"],["autumn","秋天"],["cool","涼爽"],["too hot","太熱"]], ex:"My favorite season is autumn because it's cool and not too hot."},
  {id:"q22", lv:2, t:"alltag", en:"What was your favorite food when you were a child?", zh:"你小時候最喜歡吃什麼？", start:"When I was a child, I loved ...", w:[["my mom's cooking","媽媽煮的菜"],["candy","糖果"],["ice cream","冰淇淋"],["sweet","甜的"]], ex:"When I was a child, I loved my grandmother's dumplings."},
  {id:"q23", lv:2, t:"alltag", en:"Where would you like to travel? Why?", zh:"你想去哪裡旅行？為什麼？", start:"I would like to go to ... because ...", w:[["beautiful","美"],["culture","文化"],["nature","大自然"],["the food","食物"]], ex:"I would like to go to New Zealand because the nature is beautiful."},
  {id:"q24", lv:2, t:"alltag", en:"How did you learn English?", zh:"你是怎麼學英文的？", start:"I learned English ...", w:[["at school","在學校"],["from movies","看電影"],["songs","歌"],["by myself","自己"]], ex:"I learned English at school, and later from movies and songs."},
  {id:"q25", lv:2, t:"alltag", en:"What did you do on your last birthday?", zh:"你上次生日做了什麼？", start:"On my last birthday I ...", w:[["cake","蛋糕"],["celebrated","慶祝"],["a present","禮物"],["a restaurant","餐廳"]], ex:"On my last birthday I went to a nice restaurant with my family."},
  {id:"q26", lv:2, t:"meinung", en:"What makes you happy?", zh:"什麼事情會讓你開心？", start:"I feel happy when ...", w:[["sunny days","晴天"],["good food","好吃的東西"],["my family","我的家人"],["a day off","放假"]], ex:"I feel happy when I have a day off and the weather is nice."},
  {id:"q27", lv:2, t:"situation", en:"You are at a hotel. The air conditioner doesn't work. Call the front desk.", zh:"你在飯店，冷氣壞了。打電話給櫃檯。", start:"Hello, this is room ... The air conditioner ...", w:[["doesn't work","壞了"],["could you send someone","可以派人來嗎"],["room","房間"],["hot","熱"]], ex:"Hello, this is room 512. The air conditioner doesn't work. Could you send someone, please?"},
  {id:"q28", lv:2, t:"situation", en:"At a restaurant, your food is cold. Tell the waiter politely.", zh:"在餐廳，你的菜是冷的。客氣地跟服務生說。", start:"Excuse me, my ... is cold. Could you ...", w:[["warm it up","加熱"],["waiter","服務生"],["soup","湯"],["a little","有一點"]], ex:"Excuse me, my soup is a little cold. Could you warm it up, please?"},
  {id:"q29", lv:2, t:"situation", en:"You are at the airport. Your suitcase didn't arrive.", zh:"你在機場，你的行李沒有到。", start:"Excuse me, my suitcase didn't arrive.", w:[["suitcase","行李箱"],["flight","班機"],["black","黑色的"],["hotel","飯店"]], ex:"Excuse me, my suitcase didn't arrive. It's black and very big. I came on the flight from Taipei."},
  {id:"q30", lv:2, t:"situation", en:"Call a restaurant and book a table.", zh:"打電話給餐廳訂位。", start:"Hi, I'd like to book a table for ...", w:[["tonight","今天晚上"],["seven o'clock","七點"],["people","人"],["my name is","我的名字是"]], ex:"Hi, I'd like to book a table for four people tonight at seven o'clock."},
  {id:"q31", lv:2, t:"situation", en:"At the doctor's: tell the doctor what's wrong.", zh:"看醫生：告訴醫生你哪裡不舒服。", start:"I don't feel well. I have ...", w:[["headache","頭痛"],["sore throat","喉嚨痛"],["fever","發燒"],["cough","咳嗽"]], ex:"I don't feel well. I have a sore throat and a little fever."},
  {id:"q32", lv:2, t:"situation", en:"A friend invites you to dinner, but you can't come. Say no politely.", zh:"朋友邀請你吃晚餐，但是你不能去。客氣地拒絕。", start:"Thank you so much, but ...", w:[["I'm busy","我在忙"],["maybe next time","下次吧"],["I'm sorry","不好意思"],["another day","改天"]], ex:"Thank you so much, but I'm busy on Friday. Maybe next time?"},
  {id:"q33", lv:2, t:"situation", en:"You are at a pharmacy. Ask for something for a cold.", zh:"你在藥局，想買感冒藥。", start:"Hi, do you have something for ...", w:[["a cold","感冒"],["a runny nose","流鼻水"],["how often","多久一次"],["tablets","藥片"]], ex:"Hi, do you have something for a cold? I have a runny nose."},
  {id:"q34", lv:2, t:"situation", en:"You missed your train. Ask about the next one.", zh:"你錯過了火車，問下一班車。", start:"Excuse me, I missed my train. When is the next ...", w:[["next train","下一班火車"],["platform","月台"],["ticket","票"],["change","換"]], ex:"Excuse me, I missed my train to Tainan. When is the next one? Can I use the same ticket?"},
  {id:"q35", lv:2, t:"situation", en:"Check in at a hotel.", zh:"你在飯店辦入住。", start:"Hi, I have a reservation under the name ...", w:[["reservation","訂房"],["two nights","兩晚"],["breakfast","早餐"],["what time","幾點"]], ex:"Hi, I have a reservation under the name Kyla, for two nights. What time is breakfast?"},
  {id:"q36", lv:2, t:"situation", en:"Ask a stranger to take a photo of you.", zh:"請陌生人幫你拍照。", start:"Excuse me, could you ...", w:[["take a photo","拍照"],["one more","再一張"],["press here","按這裡"],["thank you so much","非常感謝"]], ex:"Excuse me, could you take a photo of us? Just press here. Thank you so much!"},
  // Stufe 3
  {id:"q37", lv:3, t:"meinung", en:"Is it better to live in a city or in the countryside? Why?", zh:"住在城市比較好，還是住在鄉下比較好？為什麼？", start:"I think it's better to live in ... because ...", w:[["quiet","安靜"],["convenient","方便"],["nature","大自然"],["crowded","擁擠"]], ex:"I think it's better to live in the city because it's more convenient, but the countryside is quieter."},
  {id:"q38", lv:3, t:"alltag", en:"Have you ever been abroad? Where?", zh:"你出過國嗎？去過哪裡？", start:"Yes, I have been to ...", w:[["abroad","國外"],["twice","兩次"],["never","從來沒有"],["last year","去年"]], ex:"Yes, I have been to Japan twice and to Thailand once."},
  {id:"q39", lv:3, t:"alltag", en:"What is something you have never done, but want to try?", zh:"有什麼事情你從來沒做過，但是想試試看？", start:"I have never ..., but I want to try it.", w:[["diving","潛水"],["skiing","滑雪"],["a marathon","馬拉松"],["alone","一個人"]], ex:"I have never gone diving, but I want to try it one day."},
  {id:"q40", lv:3, t:"meinung", en:"What would you do with a free week?", zh:"如果你有一個禮拜的假，你會做什麼？", start:"If I had a free week, I would ...", w:[["travel","旅行"],["sleep","睡覺"],["relax","放鬆"],["the beach","海邊"]], ex:"If I had a free week, I would go to the beach and read a lot of books."},
  {id:"q41", lv:3, t:"meinung", en:"What do you think about social media?", zh:"你覺得社群媒體怎麼樣？", start:"I think social media is ... because ...", w:[["useful","有用"],["waste of time","浪費時間"],["stay in touch","保持聯絡"],["too much","太多"]], ex:"I think social media is useful because I can stay in touch with my friends, but I use it too much."},
  {id:"q42", lv:3, t:"meinung", en:"Is English important for you? Why?", zh:"英文對你來說重要嗎？為什麼？", start:"English is important for me because ...", w:[["travel","旅行"],["work","工作"],["understand","聽懂"],["talk to people","跟別人說話"]], ex:"English is important for me because I want to talk to people when I travel."},
  {id:"q43", lv:3, t:"meinung", en:"What advice would you give to a tourist in Taiwan?", zh:"你會給來台灣的觀光客什麼建議？", start:"You should ...", w:[["night market","夜市"],["EasyCard","悠遊卡"],["try","試試看"],["don't miss","不要錯過"]], ex:"You should buy an EasyCard and try the food at a night market."},
  {id:"q44", lv:3, t:"meinung", en:"Do you prefer to travel alone or with other people? Why?", zh:"你比較喜歡一個人旅行，還是跟別人一起？為什麼？", start:"I prefer to travel ... because ...", w:[["alone","一個人"],["with friends","跟朋友"],["free","自由"],["safer","比較安全"]], ex:"I prefer to travel with friends because it's more fun and safer."},
  {id:"q45", lv:3, t:"alltag", en:"How has your city changed in the last few years?", zh:"你住的城市這幾年有什麼改變？", start:"In the last few years, ...", w:[["more expensive","變貴了"],["new buildings","新大樓"],["more crowded","更擁擠"],["better","變好"]], ex:"In the last few years, my city has become more expensive, but there are more parks now."},
  {id:"q46", lv:3, t:"meinung", en:"What is the best decision you have ever made?", zh:"你做過最好的決定是什麼？", start:"The best decision I have ever made was ...", w:[["to move","搬家"],["to quit","辭職"],["to start","開始"],["to learn","學"]], ex:"The best decision I have ever made was to move to a smaller apartment near the park."},
  {id:"q47", lv:3, t:"meinung", en:"Is it better to cook at home or to eat out?", zh:"在家煮飯比較好，還是外食比較好？", start:"I think it's better to ... because ...", w:[["healthier","比較健康"],["cheaper","比較便宜"],["faster","比較快"],["no time","沒時間"]], ex:"I think it's better to cook at home because it's healthier, but in Taiwan eating out is very cheap."},
  {id:"q48", lv:3, t:"situation", en:"Your neighbor is very loud at night. Talk to them politely.", zh:"你的鄰居晚上很吵。客氣地跟他說。", start:"Hi, sorry to bother you, but ...", w:[["loud","吵"],["at night","晚上"],["sleep","睡覺"],["would you mind","你介意……嗎"]], ex:"Hi, sorry to bother you, but it's very loud at night and I can't sleep. Would you mind turning the music down?"},
  {id:"q49", lv:3, t:"situation", en:"You bought a shirt, but it's too small. Take it back to the shop.", zh:"你買了一件襯衫，但是太小了。拿回店裡退換。", start:"Hi, I bought this shirt yesterday, but ...", w:[["return","退貨"],["exchange","換貨"],["receipt","收據"],["refund","退錢"]], ex:"Hi, I bought this shirt yesterday, but it's too small. Can I exchange it for a bigger size? Here is the receipt."},
  {id:"q50", lv:3, t:"situation", en:"You want to change your hotel room. Explain why.", zh:"你想換飯店房間，說明原因。", start:"Excuse me, could I change my room? ...", w:[["noisy","吵"],["it smells","有味道"],["the view","景觀"],["another room","另一間房"]], ex:"Excuse me, could I change my room? It's very noisy because it's next to the elevator."},
  {id:"q51", lv:3, t:"situation", en:"Someone is sitting in your seat on the train.", zh:"火車上有人坐了你的位子。", start:"Excuse me, I think this is my seat.", w:[["seat","座位"],["ticket","票"],["car number","車廂號碼"],["no problem","沒關係"]], ex:"Excuse me, I think this is my seat. My ticket says car five, seat twelve."},
  {id:"q52", lv:3, t:"situation", en:"A tourist asks you for a good restaurant nearby. Help them.", zh:"一位觀光客問你附近有沒有好餐廳。幫他一下。", start:"There is a good ... near here.", w:[["around the corner","轉角"],["walk","走路"],["minutes","分鐘"],["famous for","有名的是"]], ex:"There is a good noodle shop near here. Walk straight for five minutes, and it's on the left. It's famous for beef noodles."},
  {id:"q53", lv:3, t:"meinung", en:"What is more important to you: money or free time? Why?", zh:"對你來說，錢比較重要還是自由時間比較重要？為什麼？", start:"For me, ... is more important because ...", w:[["money","錢"],["free time","自由時間"],["stress","壓力"],["family","家人"]], ex:"For me, free time is more important because I want to spend time with my family."},
  {id:"q54", lv:3, t:"meinung", en:"Should children learn English very early? Why or why not?", zh:"小孩應該很早就開始學英文嗎？為什麼？", start:"I think children should ... because ...", w:[["early","早"],["play","玩"],["pressure","壓力"],["natural","自然"]], ex:"I think children should learn English early, but with games and songs, not with pressure."},
];

// Erzaehlen / Meinung: 2-3 Saetze, mit Leitfragen. g = [englisch, chinesisch].
const ERZAEHLEN = [
  {id:"s1",  lv:2, en:"Tell me about a nice trip you took.", zh:"說說一次你很喜歡的旅行。", g:[["Where did you go?","你去了哪裡？"],["Who did you go with?","跟誰去？"],["What did you do there?","你在那裡做了什麼？"]], ex:"Two years ago I went to Hualien with my friends. We stayed in a small hotel near the sea. We went hiking in Taroko, and the food was great."},
  {id:"s2",  lv:2, en:"Describe a normal day in your life.", zh:"描述一下你平常的一天。", g:[["What do you do in the morning?","早上做什麼？"],["And in the afternoon?","下午呢？"],["And in the evening?","晚上呢？"]], ex:"I get up at seven and drink coffee. In the afternoon I work or go shopping. In the evening I cook and watch a TV show."},
  {id:"s3",  lv:2, en:"Tell me about your favorite restaurant.", zh:"說說你最喜歡的餐廳。", g:[["Where is it?","在哪裡？"],["What food do they have?","有什麼菜？"],["Why do you like it?","你為什麼喜歡？"]], ex:"My favorite restaurant is a small hot pot place near my home. The soup is very good and it's not expensive. I go there with my family."},
  {id:"s4",  lv:2, en:"Describe a person you love.", zh:"描述一位你愛的人。", g:[["Who is it?","是誰？"],["What is this person like?","這個人是什麼樣的人？"],["What do you do together?","你們一起做什麼？"]], ex:"I love my mother. She is very kind and a little funny. We often cook together and talk for hours."},
  {id:"s5",  lv:2, en:"Tell me about a Taiwanese holiday you like.", zh:"說說一個你喜歡的台灣節日。", g:[["Which holiday is it?","哪個節日？"],["What do you do?","你都做什麼？"],["What do you eat?","你們吃什麼？"]], ex:"I like Chinese New Year. The whole family comes together. We eat a big dinner and give red envelopes to the children."},
  {id:"s6",  lv:2, en:"Tell me about your last birthday.", zh:"說說你上次的生日。", g:[["What did you do?","你做了什麼？"],["Who was there?","誰在？"],["Did you get a present?","你有收到禮物嗎？"]], ex:"On my last birthday I went to a nice restaurant with my family. They gave me a beautiful scarf. It was a quiet but happy day."},
  {id:"s7",  lv:2, en:"Describe your neighborhood.", zh:"描述一下你家附近。", g:[["What is there?","有什麼？"],["What do you like?","你喜歡什麼？"],["What don't you like?","你不喜歡什麼？"]], ex:"There are many small shops and a park near my home. I like the breakfast shop on the corner. I don't like the traffic, because it's very loud."},
  {id:"s8",  lv:2, en:"Tell me about a movie or TV show you like.", zh:"說說一部你喜歡的電影或影集。", g:[["What is it called?","叫什麼名字？"],["What is it about?","在講什麼？"],["Why do you like it?","你為什麼喜歡？"]], ex:"I like a Korean TV show about a family. It's about a woman who opens a small restaurant. I like it because it's funny and a little sad."},
  {id:"s9",  lv:3, en:"Something went wrong on a trip. What happened?", zh:"旅行的時候出了問題，發生了什麼事？", g:[["Where were you?","你在哪裡？"],["What happened?","發生了什麼事？"],["What did you do?","你怎麼處理？"]], ex:"I was in Bangkok, and I lost my wallet on the first day. I went to the police and called my bank. A nice woman at the hotel helped me a lot."},
  {id:"s10", lv:3, en:"Talk about a time when you were very happy.", zh:"說說一次你非常開心的時候。", g:[["When was it?","什麼時候？"],["What happened?","發生了什麼事？"],["Why were you so happy?","你為什麼那麼開心？"]], ex:"I was very happy when my friend came back from Canada. We hadn't seen each other for five years. We talked all night."},
  {id:"s11", lv:3, en:"What would your perfect day look like?", zh:"你理想中完美的一天是什麼樣子？", g:[["Where would you be?","你會在哪裡？"],["Who would be with you?","誰會跟你在一起？"],["What would you do?","你會做什麼？"]], ex:"My perfect day would start with a late breakfast by the sea. I would spend the day with my best friends. In the evening we would have a barbecue on the beach."},
  {id:"s12", lv:3, en:"Talk about something you learned recently.", zh:"說說你最近學到的一件事。", g:[["What did you learn?","你學了什麼？"],["How did you learn it?","你怎麼學的？"],["Was it difficult?","難嗎？"]], ex:"Recently I learned how to make bread. I watched videos on YouTube and tried many times. It was difficult at first, but now it's easy."},
  {id:"s13", lv:3, en:"What are the good and bad things about living in Taiwan?", zh:"住在台灣有什麼好處和壞處？", g:[["What is good?","什麼好？"],["What is not so good?","什麼不太好？"],["Would you live somewhere else?","你會想住別的地方嗎？"]], ex:"The food is great and everything is very convenient. But the summer is too hot and the cities are crowded. I would like to live abroad for a year, but not forever."},
  {id:"s14", lv:3, en:"How has your life changed in the last ten years?", zh:"這十年來，你的生活有什麼改變？", g:[["Where did you live then?","那時候住哪裡？"],["What is different now?","現在有什麼不一樣？"],["Is your life better now?","現在比較好嗎？"]], ex:"Ten years ago I lived with my parents. Now I have my own apartment and a different job. I think my life is calmer now."},
  {id:"s15", lv:3, en:"Tell me about a time when you had to speak English. How did it go?", zh:"說說一次你必須說英文的經驗。結果怎麼樣？", g:[["Where were you?","你在哪裡？"],["Who did you talk to?","你跟誰說話？"],["How did you feel?","你覺得怎麼樣？"]], ex:"Last year I had to ask for help at an airport in Singapore. I was very nervous, but the man was friendly. In the end, he understood me and I felt proud."},
  {id:"s16", lv:3, en:"Recommend a place in Taiwan to a friend.", zh:"跟朋友推薦一個台灣的地方。", g:[["Where is it?","在哪裡？"],["What can you do there?","在那裡可以做什麼？"],["When should they go?","什麼時候去最好？"]], ex:"You should go to Alishan. You can see the sunrise and walk in the forest. The best time to go is in spring, when the cherry blossoms are out."},
  {id:"s17", lv:3, en:"Tell me about your dream life.", zh:"說說你夢想中的生活。", g:[["Where would you live?","你會住在哪裡？"],["What would you do every day?","你每天會做什麼？"],["Who would be with you?","誰會跟你在一起？"]], ex:"I would live in a small house near the mountains. Every morning I would work in my garden. My family and my two dogs would be with me."},
  {id:"s18", lv:3, en:"Is it better to cook at home or to eat out? Give two reasons.", zh:"在家煮飯比較好，還是外食比較好？說兩個理由。", g:[["What do you prefer?","你比較喜歡哪一個？"],["Reason one?","第一個理由？"],["Reason two?","第二個理由？"]], ex:"I prefer to cook at home. First, it's healthier because I use less oil and salt. Second, cooking helps me relax after a long day."},
];
